spring:
  application:
    name: smart-wallet

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    web:
      pageable:
        max-page-size: 100

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}