spring:
  application:
    name: smart-wallet
  data:
    web:
      pageable:
        max-page-size: 100
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}